name: football
description: Shows the current ranking of top European football teams. The ranking based on the market values ​​is recalculated daily.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

#  assets:
#    - assets/config.json